name: "Windows Smoke Tests"

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: "Run Smoke Tests"
    runs-on: windows-latest
    steps:
      - name: Install Dagger CLI
        run: Invoke-WebRequest -UseBasicParsing -Uri https://dl.dagger.io/dagger/install.ps1 | Invoke-Expression
      - name: Check PWD
        run: pwd
      - name: Check Path
        run: $env:path
      - name: Check Tree
        run: tree
      - name: Verify Install
        run: D:\a\dagger\dagger\dagger\dagger.exe version